### ISSUE TITLE
Possible Transportation Change - Trains to Planes 

### ISSUE THREAD

**Issue by rcgilbert** [rcgilbert/RunningTrain#1]
I brought up the idea for this app with a few people and they really liked the idea.  However, the general consensus I got from them is that airlines would be more attractive since people could place bets as they were waiting for their planes generating greater user engagement.  The conversation then digressed into how this app could create a small amount of accountability for the airlines since we could rank airlines on how often they're late.

**Comment by Kiplol** [comment]
That is brilliant.  

## 

Kip
